//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbAMCEntities : DbContext
    {
        public dbAMCEntities()
            : base("name=dbAMCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblERPatientChiefComplaint> tblERPatientChiefComplaints { get; set; }
        public virtual DbSet<tblERPatientDocument> tblERPatientDocuments { get; set; }
        public virtual DbSet<tblERPatientInvestigation> tblERPatientInvestigations { get; set; }
        public virtual DbSet<tblERPatientPastHistory> tblERPatientPastHistories { get; set; }
        public virtual DbSet<tblDrugRoute> tblDrugRoutes { get; set; }
        public virtual DbSet<tblException> tblExceptions { get; set; }
        public virtual DbSet<tblERPatientPackageOrder> tblERPatientPackageOrders { get; set; }
        public virtual DbSet<tblDeathCertificate> tblDeathCertificates { get; set; }
        public virtual DbSet<tblDischargeSummary> tblDischargeSummaries { get; set; }
        public virtual DbSet<tblERDischargeMedicine> tblERDischargeMedicines { get; set; }
        public virtual DbSet<tblLAMA> tblLAMAs { get; set; }
        public virtual DbSet<tblPatientReferral> tblPatientReferrals { get; set; }
        public virtual DbSet<tblClinicalDocumentER> tblClinicalDocumentERs { get; set; }
        public virtual DbSet<tblERPatientDrugAllergy> tblERPatientDrugAllergies { get; set; }
        public virtual DbSet<tblERPatientReviewForm> tblERPatientReviewForms { get; set; }
        public virtual DbSet<tblERPatient> tblERPatients { get; set; }
        public virtual DbSet<tblIPDAdmOrder> tblIPDAdmOrders { get; set; }
        public virtual DbSet<tblIPDAdmPrescriptionOrder> tblIPDAdmPrescriptionOrders { get; set; }
        public virtual DbSet<tblIPDAdmServiceOrder> tblIPDAdmServiceOrders { get; set; }
        public virtual DbSet<tblIPDAdmServiceInst> tblIPDAdmServiceInsts { get; set; }
        public virtual DbSet<tblERPatientVital> tblERPatientVitals { get; set; }
        public virtual DbSet<tblClinicalDocument> tblClinicalDocuments { get; set; }
    }
}
