//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDischargeSummary
    {
        public long intDischargeSummaryCode { get; set; }
        public long intPatientCode { get; set; }
        public Nullable<long> intIPDAdmissionCode { get; set; }
        public Nullable<long> intERAdmissionCode { get; set; }
        public System.DateTime dtmDischarge { get; set; }
        public string strFinalDiagnosis { get; set; }
        public string strBriefHistory { get; set; }
        public string strProcedure { get; set; }
        public string strDischargeMedication { get; set; }
        public string strDietInstructions { get; set; }
        public string strClinicalAssessment { get; set; }
        public string strFollowUpInstructions { get; set; }
        public Nullable<System.DateTime> dtmFollowUp { get; set; }
        public int intRestDay { get; set; }
        public bool bolIsFinal { get; set; }
        public byte[] tmVersion { get; set; }
        public System.DateTime dtmCreated { get; set; }
        public Nullable<System.DateTime> dtmLastM { get; set; }
        public int intOwnerCode { get; set; }
        public int intCreatedByCode { get; set; }
        public Nullable<int> intAlteredByCode { get; set; }
        public int intRecordStatusCode { get; set; }
        public int intBranchCode { get; set; }
        public int intCompanyCode { get; set; }
    }
}
