//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDrugRoute
    {
        public int intDrugRouteCode { get; set; }
        public string strDrugRoute { get; set; }
        public string strDrugRouteShortName { get; set; }
        public byte[] tmVersion { get; set; }
        public System.DateTime dtmCreated { get; set; }
        public Nullable<System.DateTime> dtmLastM { get; set; }
        public int intOwnerCode { get; set; }
        public int intCreatedByCode { get; set; }
        public Nullable<int> intAlteredByCode { get; set; }
        public int intRecordStatusCode { get; set; }
        public int intCompanyCode { get; set; }
    }
}
