//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeathCertificate
    {
        public long intDeathCertificateCode { get; set; }
        public long intPatientCode { get; set; }
        public Nullable<long> intIPDAdmissionCode { get; set; }
        public Nullable<long> intERAdmissionCode { get; set; }
        public long intAttendingConsultant { get; set; }
        public System.DateTime dtmDeath { get; set; }
        public string strPrimaryCause { get; set; }
        public string strSecondaryCause { get; set; }
        public bool bolIsBroughtDead { get; set; }
        public Nullable<System.DateTime> dtmBrought { get; set; }
        public string strBroughtOn { get; set; }
        public string strBroughtBy { get; set; }
        public string strMedicalCondition { get; set; }
        public string strHandOverTo { get; set; }
        public Nullable<System.DateTime> dtmHandedOver { get; set; }
        public int intRelationCode { get; set; }
        public string strRelativeCNIC { get; set; }
        public Nullable<int> intNurseOnDutyCode { get; set; }
        public Nullable<int> intMOOnDutyCode { get; set; }
        public bool bolIsFinal { get; set; }
        public byte[] tmVersion { get; set; }
        public System.DateTime dtmCreated { get; set; }
        public Nullable<System.DateTime> dtmLastM { get; set; }
        public int intOwnerCode { get; set; }
        public int intCreatedByCode { get; set; }
        public Nullable<int> intAlteredByCode { get; set; }
        public int intRecordStatusCode { get; set; }
        public int intBranchCode { get; set; }
        public int intCompanyCode { get; set; }
    }
}
