//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblERPatientPackageOrder
    {
        public long intERPatientPackageOrderCode { get; set; }
        public long intERPatientCode { get; set; }
        public int intPackageTypeCode { get; set; }
        public Nullable<int> intERPackageCode { get; set; }
        public Nullable<int> intERPackageDetailCode { get; set; }
        public string strItemName { get; set; }
        public string strDose { get; set; }
        public Nullable<int> intDrugRouteCode { get; set; }
        public bool bolDiscontinue { get; set; }
        public string strRemarks { get; set; }
        public Nullable<int> intDiscontinueByCode { get; set; }
        public Nullable<System.DateTime> dtmDiscontinue { get; set; }
        public bool bolIsAcknowledged { get; set; }
        public Nullable<int> intAckByCode { get; set; }
        public Nullable<System.DateTime> dtmAck { get; set; }
        public int intSortOrder { get; set; }
        public byte[] tmVersion { get; set; }
        public System.DateTime dtmCreated { get; set; }
        public Nullable<System.DateTime> dtmLastM { get; set; }
        public int intOwnerCode { get; set; }
        public int intCreatedByCode { get; set; }
        public Nullable<int> intAlteredByCode { get; set; }
        public int intRecordStatusCode { get; set; }
        public int intBranchCode { get; set; }
        public int intCompanyCode { get; set; }
    
        public virtual tblERPatient tblERPatient { get; set; }
    }
}
