//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblERPatient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblERPatient()
        {
            this.tblERPatientChiefComplaints = new HashSet<tblERPatientChiefComplaint>();
            this.tblERPatientDocuments = new HashSet<tblERPatientDocument>();
            this.tblERPatientDrugAllergies = new HashSet<tblERPatientDrugAllergy>();
            this.tblERPatientReviewForms = new HashSet<tblERPatientReviewForm>();
            this.tblERPatientInvestigations = new HashSet<tblERPatientInvestigation>();
            this.tblERPatientPackageOrders = new HashSet<tblERPatientPackageOrder>();
            this.tblERPatientPastHistories = new HashSet<tblERPatientPastHistory>();
            this.tblERPatientVitals = new HashSet<tblERPatientVital>();
        }
    
        public long intERPatientCode { get; set; }
        public int intWardBedCode { get; set; }
        public Nullable<long> intERAdmissionCode { get; set; }
        public System.DateTime dtmAdmission { get; set; }
        public string strName { get; set; }
        public Nullable<bool> bolIsDischargeStart { get; set; }
        public Nullable<System.DateTime> dtmDischargeStart { get; set; }
        public Nullable<bool> bolIsDischarge { get; set; }
        public Nullable<System.DateTime> dtmDischarge { get; set; }
        public string strTriageColor { get; set; }
        public string strHOPI { get; set; }
        public byte[] tmVersion { get; set; }
        public System.DateTime dtmCreated { get; set; }
        public Nullable<System.DateTime> dtmLastM { get; set; }
        public int intOwnerCode { get; set; }
        public int intCreatedByCode { get; set; }
        public Nullable<int> intAlteredByCode { get; set; }
        public int intRecordStatusCode { get; set; }
        public int intBranchCode { get; set; }
        public int intCompanyCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblERPatientChiefComplaint> tblERPatientChiefComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblERPatientDocument> tblERPatientDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblERPatientDrugAllergy> tblERPatientDrugAllergies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblERPatientReviewForm> tblERPatientReviewForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblERPatientInvestigation> tblERPatientInvestigations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblERPatientPackageOrder> tblERPatientPackageOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblERPatientPastHistory> tblERPatientPastHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblERPatientVital> tblERPatientVitals { get; set; }
    }
}
