//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblERDischargeMedicine
    {
        public long intERDischargeMedicineCode { get; set; }
        public long intPatientCode { get; set; }
        public long intERAdmissionCode { get; set; }
        public Nullable<long> intItemCode { get; set; }
        public string strDrugName { get; set; }
        public string strDosage { get; set; }
        public Nullable<int> intDrugFrequencyCode { get; set; }
        public Nullable<int> intDays { get; set; }
        public string strInstruction { get; set; }
        public byte[] tmVersion { get; set; }
        public System.DateTime dtmCreated { get; set; }
        public Nullable<System.DateTime> dtmLastM { get; set; }
        public int intOwnerCode { get; set; }
        public int intCreatedByCode { get; set; }
        public Nullable<int> intAlteredByCode { get; set; }
        public int intRecordStatusCode { get; set; }
        public int intBranchCode { get; set; }
        public int intCompanyCode { get; set; }
    }
}
