//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblException
    {
        public long intExceptionCode { get; set; }
        public string strFormName { get; set; }
        public string strMethod { get; set; }
        public string strDetail { get; set; }
        public string strInnerException { get; set; }
        public System.DateTime dtmException { get; set; }
        public int intUserCode { get; set; }
        public string strSystemName { get; set; }
        public string strSystemIP { get; set; }
        public int intCompanyCode { get; set; }
    }
}
