//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblERPatientVital
    {
        public long intERPatientVitalsCode { get; set; }
        public long intERPatientCode { get; set; }
        public System.DateTime dtmVitals { get; set; }
        public Nullable<int> intHeartRate { get; set; }
        public Nullable<int> intPulse { get; set; }
        public Nullable<int> intBP1 { get; set; }
        public Nullable<int> intBP2 { get; set; }
        public Nullable<int> intResp { get; set; }
        public Nullable<decimal> numTemp { get; set; }
        public Nullable<int> intHeight { get; set; }
        public Nullable<decimal> numWeight { get; set; }
        public Nullable<int> intMetricBMI { get; set; }
        public Nullable<int> intSPO2 { get; set; }
        public string strSPo2 { get; set; }
        public Nullable<decimal> numGlucoseF { get; set; }
        public Nullable<decimal> numGlucoseR { get; set; }
        public Nullable<int> intPainScore { get; set; }
        public Nullable<int> intFallRisk { get; set; }
        public Nullable<int> intConciousness { get; set; }
        public byte[] tmVersion { get; set; }
        public System.DateTime dtmCreated { get; set; }
        public Nullable<System.DateTime> dtmLastM { get; set; }
        public int intOwnerCode { get; set; }
        public int intCreatedByCode { get; set; }
        public Nullable<int> intAlteredByCode { get; set; }
        public int intRecordStatusCode { get; set; }
        public int intBranchCode { get; set; }
        public int intCompanyCode { get; set; }
    
        public virtual tblERPatient tblERPatient { get; set; }
    }
}
