//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblERPatientReviewForm
    {
        public long intERPatientReviewFormCode { get; set; }
        public long intERPatientCode { get; set; }
        public System.DateTime dtmSaved { get; set; }
        public string strPastMedicalHistory { get; set; }
        public string strFoodAllergy { get; set; }
        public string strPastSurgicalHistory { get; set; }
        public Nullable<int> intGcsCode { get; set; }
        public Nullable<int> intPlanterCode { get; set; }
        public Nullable<int> intCvsCode { get; set; }
        public Nullable<int> intRespiratoryCode { get; set; }
        public Nullable<int> intBowelSoundCode { get; set; }
        public Nullable<int> intAbdomenCode { get; set; }
        public Nullable<int> intAdmissionCategoryCode { get; set; }
        public Nullable<int> intReceivedFromCode { get; set; }
        public Nullable<int> intOutcomeCode { get; set; }
        public string strDiscussedWith { get; set; }
        public string strReferredTo { get; set; }
        public string strAssessmentDiagnosis { get; set; }
        public Nullable<int> intMedicinePackageCode { get; set; }
        public Nullable<int> intSurgicalPackageCode { get; set; }
        public Nullable<int> intConditionUponReleaseLovCode { get; set; }
        public Nullable<int> intAdrLovCode { get; set; }
        public string strTreatmentNotes { get; set; }
        public string strConsultantPlan { get; set; }
        public string strNursingObservations { get; set; }
        public string strNursingCarePlan { get; set; }
        public byte[] tmVersion { get; set; }
        public System.DateTime dtmCreated { get; set; }
        public Nullable<System.DateTime> dtmLastM { get; set; }
        public int intOwnerCode { get; set; }
        public int intCreatedByCode { get; set; }
        public Nullable<int> intAlteredByCode { get; set; }
        public int intRecordStatusCode { get; set; }
        public int intBranchCode { get; set; }
        public int intCompanyCode { get; set; }
    
        public virtual tblERPatient tblERPatient { get; set; }
    }
}
