//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIPDAdmOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblIPDAdmOrder()
        {
            this.tblIPDAdmPrescriptionOrders = new HashSet<tblIPDAdmPrescriptionOrder>();
            this.tblIPDAdmServiceOrders = new HashSet<tblIPDAdmServiceOrder>();
            this.tblIPDAdmServiceInsts = new HashSet<tblIPDAdmServiceInst>();
        }
    
        public long intIPDAdmOrderCode { get; set; }
        public Nullable<int> intIPDAdmOrderStatusCode { get; set; }
        public string strIPDAdmOrderNo { get; set; }
        public System.DateTime dtmIPDAdmOrder { get; set; }
        public System.DateTime dtAdmissionRequest { get; set; }
        public Nullable<long> intERAdmissionCode { get; set; }
        public long intPatientCode { get; set; }
        public Nullable<long> intAdmConsultantCode { get; set; }
        public Nullable<long> intReffConsultantCode { get; set; }
        public Nullable<int> intAdmissionTypeCode { get; set; }
        public Nullable<int> intAdmissionCareLevelCode { get; set; }
        public string strDiagnosis { get; set; }
        public string strDietInstruction { get; set; }
        public string strComments { get; set; }
        public string strCancelRemarks { get; set; }
        public byte[] tmVersion { get; set; }
        public System.DateTime dtmCreated { get; set; }
        public Nullable<System.DateTime> dtmLastM { get; set; }
        public int intOwnerCode { get; set; }
        public int intCreatedByCode { get; set; }
        public Nullable<int> intAlteredByCode { get; set; }
        public int intRecordStatusCode { get; set; }
        public int intBranchCode { get; set; }
        public int intCompanyCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIPDAdmPrescriptionOrder> tblIPDAdmPrescriptionOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIPDAdmServiceOrder> tblIPDAdmServiceOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIPDAdmServiceInst> tblIPDAdmServiceInsts { get; set; }
    }
}
