//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPaperless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatientReferral
    {
        public long intPatientReferralCode { get; set; }
        public long intPatientCode { get; set; }
        public Nullable<long> intIPDAdmissionCode { get; set; }
        public Nullable<long> intERAdmissionCode { get; set; }
        public System.DateTime dtmPatientReferral { get; set; }
        public string strPresentingComplaint { get; set; }
        public string strClinicalSummary { get; set; }
        public string strTreatment { get; set; }
        public string strPertinentInvestigation { get; set; }
        public string strClinicalDiagnosis { get; set; }
        public Nullable<int> intReferralReasonCode { get; set; }
        public Nullable<int> intMOOnDutyCode { get; set; }
        public bool bolIsFinal { get; set; }
        public byte[] tmVersion { get; set; }
        public System.DateTime dtmCreated { get; set; }
        public Nullable<System.DateTime> dtmLastM { get; set; }
        public int intOwnerCode { get; set; }
        public int intCreatedByCode { get; set; }
        public Nullable<int> intAlteredByCode { get; set; }
        public int intRecordStatusCode { get; set; }
        public int intBranchCode { get; set; }
        public int intCompanyCode { get; set; }
    }
}
